# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, verbose_name='título')),
                ('abstract', models.TextField(max_length=1024, verbose_name='resumo')),
            ],
            options={
                'verbose_name': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='ResearchLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_line', models.CharField(max_length=200, verbose_name='linha de pesquisa')),
                ('description', models.TextField(max_length=1024, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'linhas de pesquisa',
                'verbose_name': 'linha de pesquisa',
            },
        ),
    ]
