# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170204_1838'),
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='researches',
            field=models.ManyToManyField(related_name='projects', to='members.Member'),
        ),
    ]
