# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0002_project_researches'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='research_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='researches.ResearchLine', verbose_name='linha de pesquisa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='researches',
            field=models.ManyToManyField(related_name='projects', to='members.Member', verbose_name='Pesquisadores'),
        ),
    ]
