# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170204_1838'),
        ('researches', '0003_auto_20170204_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('publication_local', models.CharField(help_text='Congresso/Periódico onde o artigo foi publicado', max_length=200, verbose_name='local de publicação')),
                ('publication_url', models.URLField(verbose_name='link da publicação')),
                ('publication_file', models.FileField(upload_to='uploads/publications/')),
                ('authors', models.ManyToManyField(help_text='Autores vinculados ao laboratório', related_name='publications', to='members.Member', verbose_name='autores')),
            ],
            options={
                'verbose_name_plural': 'Publicações',
                'verbose_name': 'publicação',
            },
        ),
    ]
