# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0004_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(help_text='Autores vinculados ao laboratório.', related_name='publications', to='members.Member', verbose_name='autores'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_file',
            field=models.FileField(upload_to='uploads/publications/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_local',
            field=models.CharField(help_text='Congresso/Periódico onde o artigo foi publicado.', max_length=200, verbose_name='local de publicação'),
        ),
    ]
