# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0005_auto_20170204_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='research_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researches.ResearchLine', verbose_name='linha de pesquisa'),
        ),
    ]
