# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0007_auto_20170204_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='research_line',
        ),
        migrations.RemoveField(
            model_name='project',
            name='researches',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
