# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0008_auto_20170211_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchline',
            name='image',
            field=models.ImageField(default=None, upload_to='research_lines', verbose_name='imagem'),
            preserve_default=False,
        ),
    ]
