# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Orientador'), ('2', 'Estudante')], max_length=1, verbose_name='categoria')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('lattes', models.URLField(verbose_name='currículo Lattes')),
                ('avatar', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Membro',
            },
        ),
    ]
