# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.FileField(upload_to='uploads/pictures/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('1', 'Orientador'), ('2', 'Mestrando'), ('3', 'Graduando')], max_length=1, verbose_name='categoria'),
        ),
    ]
