# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170204_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200, verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'localização',
            },
        ),
    ]
