# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'localização', 'verbose_name_plural': 'localizações'},
        ),
        migrations.AddField(
            model_name='location',
            name='google_maps_api_key',
            field=models.CharField(default='', max_length=200, verbose_name='API Key do Google Maps'),
            preserve_default=False,
        ),
    ]
