# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170204_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
