# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170204_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('Orientador', 'Orientador'), ('Mestrando', 'Mestrando'), ('Graduando', 'Graduando')], max_length=30, verbose_name='categoria'),
        ),
    ]
