# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20170210_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
