# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200, verbose_name='nome do laboratório')),
                ('about', models.TextField(verbose_name='sobre')),
                ('image', models.ImageField(upload_to='about', verbose_name='imagem')),
            ],
        ),
    ]
